version: "3.8"
services:
  mysqldb:
    image: mysql:8.0.29
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=workflow
    networks:
      - default
    ports:
      - 3310:3306
    volumes:
      - db:/var/lib/mysql

  zookeeper:
    image:
      wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image:
      wurstmeister/kafka
    depends_on:
      - zookeeper
    networks:
      - default
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ZK_SERVER: zookeeper:2181
      ADVERTISED_HOST: localhost
      CONSUMER_THREADS: 5
      BROKER_ID: 1
      ADVERTISED_PORT: 9092

  prometheus:
    image: prom/prometheus:v2.30.3
    networks:
      - default
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  app:
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - default
    ports:
      - 8081:80
    volumes:
      - .m2:/root/.m2

volumes:
  db:
  prometheus-data:

networks:
  default:
    external:
      name: local-environment
