apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      role: workflow-qa
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: workflow-qa
    spec:
      containers:
        - name: workflow-qa
          image: us-central1-docker.pkg.dev/basearchitecture/quickstart-docker-repo/workflow-qa
          ports:
            - containerPort: 80