apiVersion: v1
kind: Service
metadata:
  name: workflow-lb-qa
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    role: workflow-qa
  type: LoadBalancer
  loadBalancerIP: "35.222.87.103"