apiVersion: v1
kind: Service
metadata:
  name: workflow-lb
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    role: workflow
  type: LoadBalancer
  loadBalancerIP: "34.69.117.231"